spring:
  application:
    name: ceos-app
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/ceos_prod_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # 생성되는 SQL 쿼리를 로그로 확인
        format_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    access-token: 3600000
    refresh-token: 604800000

logging:
  level:
    org.hibernate.SQL: warn
    root: INFO
    cgv_23rd.ceos: INFO
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

payment:
  server:
    url: ${PAYMENT_SERVER_URL}
  store-id: ${PAYMENT_STORE_ID}
  api-secret: ${PAYMENT_API_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
        exclude: env, heapdump, threaddump, configprops, quartz
  endpoint:
    health:
      show-details: always
